# Generated by Django 4.2.2 on 2024-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_last_update_date',
            field=models.DateField(auto_now=True, verbose_name='Last update date'),
        ),
    ]
